package com.example.spring_training.service;


import com.example.spring_training.dto.ItemOrderAcknowledgment;
import com.example.spring_training.dto.ItemOrderRequest;
import com.example.spring_training.entity.CustomerInfo;
import com.example.spring_training.entity.PaymentInfo;
import com.example.spring_training.repository.CustomerInfoRepository;
import com.example.spring_training.repository.PaymentInfoRepository;

@Service

public class ItemOrderService {
    @Autowired
    private CustomerInfoRepository customerInfoRepository;
    @Autowired
    private PaymentInfoRepository paymentInfoRepository;

    public ItemOrderAcknowledgment orderItem(ItemOrderRequest request){
        ItemOrderAcknowledgment acknowledgment= null;
        CustomerInfo customerInfo= request.getCustomerInfo();
        customerInfo=customerInfoRepository.save(customerInfo); // ID gets autogenerated and can later get stored in the payment table
        //TODO //there is no database connection yet......!
        PaymentInfo paymentInfo = request.getPaymentInfo();



    }
}
